name: Lambda Compliance Check

on:
  schedule:
    - cron: '0 15 * * *'  # Example: Run at 15:00 UTC

jobs:
  compliance_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run compliance check script
      run: python src/lambda_compliance_check.py
